In [9]:
print("EJERCICIO 01")
print()
print("¿Si se declara una variable boolean del valor -1 es True o False?")
variable = -1
print(bool(variable)) 
print()
print("cualquier valor distinto de cero se evalúa como True")
print("cualquier valor igual a cero se evalúa como False")


EJERCICIO 01

¿Si se declara una variable boolean del valor -1 es True o False?
True

cualquier valor distinto de cero se evalúa como True
cualquier valor igual a cero se evalúa como False


In [10]:
print("EJERCICIO 02")
print()
print("Construir el operador XNOR en Python")
print()
print ("Operador XNOR")
print ("a   ", "b   ", "a XNOR b") 
a = True
b = True
print (a, b, not((a or b) and not (a and b)))
a = True
b = False
print (a, b, not((a or b) and not (a and b)))
a = False
b = True
print (a, b, not((a or b) and not (a and b)))
a = False
b = False
print (a, b, not((a or b) and not (a and b)))

EJERCICIO 02

Construir el operador XNOR en Python

Operador XNOR
a    b    a XNOR b
True True True
True False False
False True False
False False True


In [11]:
print("EJERCICIO 03")
print()
print ("Abriendo la puerta")
print ("luz 1   ", "luz 2   ", "Abre Puerta") 
luz1 = True
luz2 = True
print (luz1, luz2, luz1 == luz2)
luz1 = True
luz2 = False
print (luz1, luz2, luz1 == luz2)
luz1 = False
luz2 = True
print (luz1, luz2, luz1 == luz2)
luz1 = False
luz2 = False
print (luz1, luz2, luz1 == luz2)

print ("Abriendo la puerta - Utilizando XNOR")
print ("luz 1   ", "luz 2   ", "Abre Puerta - XNOR") 
luz1 = True
luz2 = True
print (luz1, luz2, not((luz1 or luz2) and not (luz1 and luz2)))
luz1 = True
luz2 = False
print (luz1, luz2, not((luz1 or luz2) and not (luz1 and luz2)))
luz1 = False
luz2 = True
print (luz1, luz2, not((luz1 or luz2) and not (luz1 and luz2)))
luz1 = False
luz2 = False
print (luz1, luz2, not((luz1 or luz2) and not (luz1 and luz2)))

EJERCICIO 03

Abriendo la puerta
luz 1    luz 2    Abre Puerta
True True True
True False False
False True False
False False True
Abriendo la puerta - Utilizando XNOR
luz 1    luz 2    Abre Puerta - XNOR
True True True
True False False
False True False
False False True


In [12]:
print("EJERCICIO 04")
print()
print("La suma de los números 7 y 3 es un número par?")
nro1 = 7
nro2 = 3
print(nro1, " + ", nro2, " = ", nro1+nro2)
print((nro1 + nro2) % 2 == 0)

EJERCICIO 04

La suma de los números 7 y 3 es un número par?
7  +  3  =  10
True


In [13]:
print("EJERCICIO 05")
print()
print("Comparar los números 123 y 890, comprobar si tienen la misma paridad ambos pares o ambos impares")
nro1 = 123
nro2 = 890
misma_paridad = (nro1 % 2) == (nro2 % 2)
print(nro1, nro2, "¿Tienen la misma paridad?")
print(misma_paridad)

EJERCICIO 05

Comparar los números 123 y 890, comprobar si tienen la misma paridad ambos pares o ambos impares
123 890 ¿Tienen la misma paridad?
False


In [14]:
print("EJERCICIO 06")
print()
print("¿El cuadrado de 123 se encuentra en el siguiente rango? [N > 0 & N < 20000]")
nro1 = 123
nro2 = nro1 * nro1
print(nro1, " Cuadrado: ", nro2)
resultado = nro2 > 0 and nro2 < 20000
print(nro2, "está en el rango especificado? ", resultado)

EJERCICIO 06

¿El cuadrado de 123 se encuentra en el siguiente rango? [N > 0 & N < 20000]
123  Cuadrado:  15129
15129 está en el rango especificado?  True


In [15]:
print("EJERCICIO 07")
print()
print("¿El cuadrado y la suma de 2 y 2 son iguales?")
suma = 2 + 2
print("La suma es: ", suma)
cuadrado = 2 * 2
print("El cuadrado es: ", cuadrado)
print("El cuadrado y la suma son iguales? ", suma == cuadrado)

EJERCICIO 07

¿El cuadrado y la suma de 2 y 2 son iguales?
La suma es:  4
El cuadrado es:  4
El cuadrado y la suma son iguales?  True


# Sesión 06
## Retos
1. ¿Si se declara una variable boolean del valor -1 es True o False?
2. Construir el operador XNOR en Python 
    3.Imprime una tabla de verdad para la siguiente afirmación: 
    "Una puerta tiene dos interruptores que controlan dos luces la puerta sólo debe abrirse cuando las dos luces están apagadas o las dos están encendidas, caso contrario la puerta no se abre, ¿qué operador lógico se puede utilizar?" 
4. La suma de los números 7 y 3 es un número par?
5. Comparar los números 123 y 890, comprobar si tienen la misma paridad ambos pares o ambos impares 
6. ¿El cuadrado de 123 se encuentra en el siguiente rango? [N > 0 & N < 20000]
7. ¿El cuadrado y la suma de 2 y 2 son iguales? 
8. Convertir y ejecutar el archivo de la "sesion06.py" a un archivo en jupyter notebook 
