print ("JUEGO DE CARTAS - LOBA")
print ("Se necesitan dos o más jugadores para un juego simple de Loba")
print ("y gana el primero que descarte todas sus cartas.")
print ("¿Cómo descartar cartas?")
print ("1. Forma escaleras.  ")
print ("Una escalera se forma con tres o más cartas en secuencia ascendente o descendente.")
print ("1.1. Todas las cartas de una escalera deben ser del mismo color y del mismo palo.")
print ("1.2. El As puede situarse al inicio (antes del 2) o al final (después de la K) de la escalera.")
print ("1.3. El comodín reemplaza a cualquier carta en una escalera, ")
print ("sin embargo, no es posible utilizar dos comodines uno después de otro.")
print ("2. Forma tricas")
print ("Una trica se forma con tres cartas del mismo valor pero distinto palo.")
print ("3. Completa escaleras y/o tricas (Sopar)")
print ("No es imprescindible tener 3 cartas para bajar una trica o una escalera, ")
print ("sino que también es posible bajar cartas individuales o incluso dos o más cartas, ")
print ("el requisito para ello es que existan escaleras incompletas o tricas sobre la mesa.")
