print ("Encuentro de amigas")
print ("Layla: ¡Hola, Pankara!")
print ("Pankara: ¡Hola, Layla! Te cuento que fui al nuevo que abrieron por el centro.")
print ("Layla: ¡No me digas! ¿Y cómo estuvo?")
print ("Pankara: ¡Me encantó! El ambiente es acogedor, y la comida... deliciosa! ¡La carne a la parrilla estaba para chuparse los dedos!")
print ("Layla: ¡Qué bueno escuchar eso! Me estás dando hambre con solo escucharte.")
print ("Pankara: Y lo mejor de todo es que los precios son bastante accesibles. No te imaginas la calidad que ofrecen por el precio que pagamos.")
print ("Layla: Eso suena genial. Definitivamente tengo que ir a probarlo. ¿Qué más recomiendas del menú?")
print ("Pankara: Los postres están muy buenos y hay para todo gusto.")
print ("Layla: ¡Qué buena selección! Tendré que ir preparada para probar un poco de todo. ¿El servicio fue bueno?")
print ("Pankara: Sí, el servicio fue excelente. Los meseros fueron muy amables y atentos en todo momento.  Es un negocio familiar y se nota el cariño que le ponen en la atención y la preparación,")
print ("Layla: ¡Perfecto! Entonces ya sé a dónde vamos la próxima vez que salgamos a comer juntas.")
print ("Pankara: ¡Por supuesto! ¡Será una cita gastronómica que no olvidaremos!")
